### ISSUE TITLE
Unclear about the value of close/log-in options

### ISSUE THREAD

**Issue by andrewpmiller** [jgagne/jgagne.github.io#1]
Some random questions/thoughts about the behavior of this message... spurred by seeing the _Close this message or Log in_ links you've included.
- Does this message appear for any user with an ad-blocker — regardless of log in status?
- Intercom is only available/visible for users who have authenticated anyway... 
- Should this _only_ appear if a user is logged in?
- The login link/button is available in the header anyway

**Comment by jgagne** [comment]
> - Intercom is only available/visible for users who have authenticated anyway... 
> - The login link/button is available in the header anyway

- Ad-blocker message only appears to authenticated users
- No need for the extra login (link/button) behavior

> - Does this message appear for any user with an ad-blocker — regardless of log in status?
> - Should this only appear if a user is logged in?

If an ad-blocker is in use:

- Ad-blocker message only appears when a user is logged in
- Ad-blocker message only appears on the Dashboard page

Questions:

- Does the message appear until the action to whitelist us or to disable the ad-blocker happens?
- Does the message contain a "Close Message" option (as proposed in the comp)?
- Does the message reappear upon each log in if the message is closed or does the message disappear for good?

**Comment by andrewpmiller** [comment]
All good questions — worth discussing with the team.
My thoughts:
> Does the message appear until the action to whitelist us or to disable the ad-blocker happens?
Yes
> Does the message contain a "Close Message" option (as proposed in the comp)?
Yes — but perhaps it's not an inline text link, and rather a small [X] in the top right?
> Does the message reappear upon each log in if the message is closed or does the message disappear for good?
Yes — for each session maybe?

**Comment by jgagne** [comment]
> Yes — but perhaps it's not an inline text link, and rather a small [X] in the top right?

Updated comps to show _no close option_, _close option text_, and _close option [✕]_.

**Comment by caweber** [comment]
To weigh in on this, I agree that an X in the top right of the message is best. Secondly, I would remove the bullet in the message as bullets should only be used when there is more than one item in a list.

Other than that, I think we should make this live and monitor it to see how effective it is. If it is not making a dent in the quantity of folks who use ad blockers, we can consider being "louder".
